// <auto-generated />
using System;
using DataLoaderWithEFCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLoaderWithEFCore.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataLoaderWithEFCore.Data.Models.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<Guid>("MovieId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new { Id = new Guid("5ff76e2f-699f-41b1-8521-e633afac4141"), CountryCode = "UK", MovieId = new Guid("a9d69485-4980-467c-8afe-f385935d1b86"), Name = "Rowan Atkinson" },
                        new { Id = new Guid("11423353-4745-44e9-91ce-65cb4bc0e8b7"), CountryCode = "FR", MovieId = new Guid("a9d69485-4980-467c-8afe-f385935d1b86"), Name = "Olga Kurylenko" },
                        new { Id = new Guid("fe22e6da-c921-40b7-8b1b-782a03260e6d"), CountryCode = "US", MovieId = new Guid("a9d69485-4980-467c-8afe-f385935d1b86"), Name = "Jake Lacy" },
                        new { Id = new Guid("a39df656-711b-4386-abbc-8deaf4f24d09"), CountryCode = "US", MovieId = new Guid("95e03cd2-1b4d-4300-8d7c-56bdf8aae646"), Name = "Bradley Cooper" },
                        new { Id = new Guid("8eb4ac98-6cca-4bfb-a067-bf9fd863fcc5"), CountryCode = "US", MovieId = new Guid("95e03cd2-1b4d-4300-8d7c-56bdf8aae646"), Name = "Lady Gaga" },
                        new { Id = new Guid("65d3c8d6-cef8-4647-acb0-c8d5c9cb5bbc"), CountryCode = "US", MovieId = new Guid("95e03cd2-1b4d-4300-8d7c-56bdf8aae646"), Name = "Sam Elliott" },
                        new { Id = new Guid("fc30f61b-b013-4590-999e-4f0a93704015"), CountryCode = "US", MovieId = new Guid("95e03cd2-1b4d-4300-8d7c-56bdf8aae646"), Name = "Andrew Dice Clay" },
                        new { Id = new Guid("1baa4cc1-e148-4fa0-8e68-ed0089a0bdce"), CountryCode = "US", MovieId = new Guid("95e03cd2-1b4d-4300-8d7c-56bdf8aae646"), Name = "Dave Chappelle" },
                        new { Id = new Guid("d84898af-ce94-4dd4-8c8e-4ee525a33117"), CountryCode = "US", MovieId = new Guid("95e03cd2-1b4d-4300-8d7c-56bdf8aae646"), Name = "Rebecca Field" },
                        new { Id = new Guid("67df57b2-a8d2-41e1-8c46-fe0e68514e9b"), CountryCode = "US", MovieId = new Guid("95e03cd2-1b4d-4300-8d7c-56bdf8aae646"), Name = "Michael Harney" },
                        new { Id = new Guid("e0d6cadf-ce5d-410c-8a19-5e20944051ce"), CountryCode = "US", MovieId = new Guid("95e03cd2-1b4d-4300-8d7c-56bdf8aae646"), Name = "Rafi Gavron" },
                        new { Id = new Guid("4e79963d-00ad-4019-9d61-730505997022"), CountryCode = "US", MovieId = new Guid("95e03cd2-1b4d-4300-8d7c-56bdf8aae646"), Name = "Willam Belli" },
                        new { Id = new Guid("260d7ea3-0f21-49bf-8aa5-8ccf8bd62d22"), CountryCode = "US", MovieId = new Guid("95e03cd2-1b4d-4300-8d7c-56bdf8aae646"), Name = "Halsey" }
                    );
                });

            modelBuilder.Entity("DataLoaderWithEFCore.Data.Models.Country", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2);

                    b.Property<string>("Name");

                    b.HasKey("Code");

                    b.ToTable("Countries");

                    b.HasData(
                        new { Code = "UK", Name = "United Kingdom" },
                        new { Code = "FR", Name = "France" },
                        new { Code = "US", Name = "United States" }
                    );
                });

            modelBuilder.Entity("DataLoaderWithEFCore.Data.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("ReleaseDateUtc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new { Id = new Guid("a9d69485-4980-467c-8afe-f385935d1b86"), Genre = "Action/Adventure", ReleaseDateUtc = new DateTime(2018, 10, 12, 2, 0, 0, 0, DateTimeKind.Local), Title = "Johnny English Strikes Again" },
                        new { Id = new Guid("95e03cd2-1b4d-4300-8d7c-56bdf8aae646"), Genre = "Drama/Romance", ReleaseDateUtc = new DateTime(2018, 10, 4, 2, 0, 0, 0, DateTimeKind.Local), Title = "A Star Is Born" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
