name: .NET Core

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.103

      - name: Build solution
        run: |
          git submodule update --init --recursive
          dotnet restore Conventions.sln
          dotnet build -c Release src/GraphQL.Conventions/GraphQL.Conventions.csproj

      - name: Run unit tests
        run: |
          dotnet test test/GraphQL.Conventions.Tests/GraphQL.Conventions.Tests.csproj

      - name: Generate NuGet package
        run: |
          dotnet pack -c Release

      - name: Install NuGet client
        uses: warrenbuckley/Setup-Nuget@v1

      - name: Add private GitHub registry to NuGet
        run: |
          nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/graphql-dotnet/index.json -Username tlil -Password ${{ secrets.GITHUB_TOKEN }}

      - name: Push generated package to GitHub registry
        run: |
          dir src\GraphQL.Conventions\bin\Release\*.nupkg
          nuget push src\GraphQL.Conventions\bin\Release\*.nupkg -Source "GPR" -SkipDuplicate
